CREATE DATABASE IF NOT EXISTS teacher_system CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE teacher_system;

CREATE TABLE IF NOT EXISTS teachers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    teacher_name VARCHAR(50) NOT NULL COMMENT '教师姓名',
    school VARCHAR(100) NOT NULL COMMENT '所在学校',
    subject VARCHAR(20) NOT NULL COMMENT '任教科目',
    phone VARCHAR(11) NOT NULL COMMENT '手机号码',
    class VARCHAR(50) NOT NULL COMMENT '任教班级',
    username VARCHAR(50) NOT NULL UNIQUE COMMENT '登录账号',
    password VARCHAR(255) NOT NULL COMMENT '登录密码',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 